name: lint and test code

on:
    push 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '17.x'
            - run: npm ci
            - run: npm run lint --if-present
            - run: npm run test --if-present
            - run: npm run build --if-present
